name: King Of Kings Jukebox â€“ Full Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install pyinstaller
        pip install kivy
        pip install pillow
        pip install pygame
        pip install numpy

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller main.py ^
        --name "KingOfKingsJukebox" ^
        --windowed ^
        --noconsole ^
        --onefile ^
        --icon=icon.ico ^
        --add-data "main.kv;." ^
        --add-data "extra.kv;." ^
        --add-data "theme_manager.kv;." ^
        --add-data "settings.json;." ^
        --add-data "sample_track.mp3;." ^
        --add-data "index.html;." ^
        --collect-all kivy

    - name: Create ZIP Package
      run: |
        powershell Compress-Archive -Path dist\KingOfKingsJukebox.exe -DestinationPath KingOfKingsJukebox_Full.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: KingOfKingsJukebox_Full_Build
        path: |
          dist/KingOfKingsJukebox.exe
          KingOfKingsJukebox_Full.zip
